#!/usr/bin/with-contenv bash

GAME_START=${GAME_START:-"+exec server.cfg"}

if ! pgrep -f quakedock >/dev/null; then
  cd /opt/quake2
  HOME=/mnt/config/home s6-setuidgid guardian screen -dmS quakedock ./q2ded -datadir /mnt/config/data/quake2 ${GAME_START};
fi
sleep 10
while pgrep -f quakedock >/dev/null; do
  sleep 30
done
