#!/usr/bin/with-contenv bash

GAME_START=${GAME_START:-"+exec server.cfg"}

if ! pgrep -f quakedock >/dev/null; then
  cd /opt/quake2
  if [[ -d /mnt/shared/data/quake2 ]]; then
    HOME=/mnt/config/home s6-setuidgid guardian screen -dmS quakedock ./q2ded -datadir /mnt/shared/data/quake2 +set basepath /mnt/shared/data/quake2 +set savepath /mnt/config/home/.yq2 ${GAME_START};
  else
    HOME=/mnt/config/home s6-setuidgid guardian screen -dmS quakedock ./q2ded -datadir /mnt/config/data/quake2 +set basepath /mnt/config/data/quake2 +set savepath /mnt/config/home/.yq2 ${GAME_START};
  fi
fi
sleep 10
while pgrep -f quakedock >/dev/null; do
  sleep 30
done
