#!/command/with-contenv /bin/bash
# SPDX-FileCopyrightText: 2020-2025 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: ISC

# shellcheck shell=bash
# shellcheck disable=SC2002,SC2086

export HOME=/mnt/config/home
export GAME_START=${GAME_START:-"+exec server.cfg"}

if [ -z "${QUAKE2_DATA}" ]; then
  if [ -n "${QUAKE2_INSTALL}" ] && [ ! "${QUAKE2_INSTALL}" = "true" ] && [ ! "${QUAKE2_INSTALL}" = "false" ]; then
    export QUAKE2_DATA="${QUAKE2_INSTALL}"
  else
    export QUAKE2_DATA="/mnt/config/data/quake2"
  fi
fi

if [[ -f "${HOME}/.yq2/baseq2/qconsole.log" ]]; then
  /bin/ls -la "${HOME}/.yq2/baseq2/qconsole.log" | /command/s6-setuidgid guardian /usr/bin/tee -a /mnt/config/log/qconsole.log
  /bin/cat "${HOME}/.yq2/baseq2/qconsole.log" | /command/s6-setuidgid guardian /usr/bin/tee -a /mnt/config/log/qconsole.log
  /bin/rm -f "${HOME}/.yq2/baseq2/qconsole.log"
fi

if [[ ! -d "${QUAKE2_DATA}/openffa/highscores" && -d /opt/quake2/openffa/highscores ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p "${QUAKE2_DATA}/openffa/highscores"
  if [[ -d "${QUAKE2_DATA}/openffa/highscores" ]]; then
    /command/s6-setuidgid guardian /bin/cp -Rv /opt/quake2/openffa/highscores/. "${QUAKE2_DATA}/openffa/highscores/"
    /bin/rm -rf /opt/quake2/openffa/highscores
  fi
fi
if [[ ! -d "${QUAKE2_DATA}/openffa/mapcfg" && -d /opt/quake2/openffa/mapcfg ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p "${QUAKE2_DATA}/openffa/mapcfg"
  if [[ -d "${QUAKE2_DATA}/openffa/mapcfg" ]]; then
    /command/s6-setuidgid guardian /bin/cp -Rv /opt/quake2/openffa/mapcfg/. "${QUAKE2_DATA}/openffa/mapcfg/"
    /bin/rm -rf /opt/quake2/openffa/mapcfg
  fi
fi
if [[ ! -d "${QUAKE2_DATA}/openffa/motd" && -d /opt/quake2/openffa/motd ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p "${QUAKE2_DATA}/openffa/motd"
  if [[ -d "${QUAKE2_DATA}/openffa/motd" ]]; then
    /command/s6-setuidgid guardian /bin/cp -Rv /opt/quake2/openffa/motd/. "${QUAKE2_DATA}/openffa/motd/"
    /bin/rm -rf /opt/quake2/openffa/motd
  fi
fi
if [[ -d /opt/quake2/openffa ]]; then
  if [[ -d "${QUAKE2_DATA}/openffa/highscores" && ! -d /opt/quake2/openffa/highscores ]]; then
    /bin/cp -Rvsp "${QUAKE2_DATA}/openffa/highscores" /opt/quake2/openffa/
  fi
  if [[ -d "${QUAKE2_DATA}/openffa/mapcfg" && ! -d /opt/quake2/openffa/mapcfg ]]; then
    /bin/cp -Rvsp "${QUAKE2_DATA}/openffa/mapcfg" /opt/quake2/openffa/
  fi
  if [[ -d "${QUAKE2_DATA}/openffa/motd" && ! -d /opt/quake2/openffa/motd ]]; then
    /bin/cp -Rvsp "${QUAKE2_DATA}/openffa/motd" /opt/quake2/openffa/
  fi
fi

cd /opt/quake2 || exit 1
/command/s6-setuidgid guardian /usr/bin/screen -dmS quakedock ./q2ded -datadir "${QUAKE2_DATA}" +set basepath "${QUAKE2_DATA}" +set savepath /mnt/config/home/.yq2 ${GAME_START}

if [[ -f ${HOME}/.screenrc ]]; then
  /bin/chown guardian:users ${HOME}
  /bin/chown guardian:users ${HOME}/.screenrc
fi
sleep 5

while /usr/bin/pgrep -f quakedock >/dev/null; do
  sleep 60
done
