---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-latest
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/quake2-server:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/quake2-server:latest
  - docker tag pdr.nephatrine.net/nephatrine/quake2-server:latest nephatrine/quake2-server:latest
  - HOME=/mnt/config/home docker push nephatrine/quake2-server:latest
  - docker rmi pdr.nephatrine.net/nephatrine/quake2-server:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-quake2-id
    webhook_token:
      from_secret: wh-quake2-tok

depends_on:
- default
---
kind: signature
hmac: 682f4a4c0c5bec6e64d66a2b63a327f467d785821a1c6d4b58ff90019954c970

...
