---
kind: pipeline
name: default

steps:
- name: local-latest
  image: plugins/docker
  settings:
    custom_dns: 192.168.20.1
    pull-image: true
    registry: pdr.nephatrine.net
    repo: nephatrine/quake2-server
    tags:
      - latest
    username:
      from_secret: docker-user-pdr
    password:
      from_secret: docker-pass-pdr
- name: remote-latest
  image: plugins/docker
  settings:
    custom_dns: 192.168.20.1
    repo: nephatrine/quake2-server
    tags:
      - latest
    username:
      from_secret: docker-user
    password:
      from_secret: docker-pass
  depends_on:
  - local-latest
- name: local-nginx
  image: plugins/docker
  settings:
    custom_dns: 192.168.20.1
    pull-image: true
    registry: pdr.nephatrine.net
    repo: nephatrine/quake2-server
    dockerfile: Dockerfile.nginx
    tags:
      - nginx
    username:
      from_secret: docker-user-pdr
    password:
      from_secret: docker-pass-pdr
  depends_on:
  - local-latest
- name: remote-nginx
  image: plugins/docker
  settings:
    custom_dns: 192.168.20.1
    repo: nephatrine/quake2-server
    dockerfile: Dockerfile.nginx
    tags:
      - nginx
    username:
      from_secret: docker-user
    password:
      from_secret: docker-pass
  depends_on:
  - local-nginx

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-quake2-id
    webhook_token:
      from_secret: wh-quake2-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 4655355472a2126353cbf2ce11592c7d6a6272c874ce46b2485ac239fad56e5e

...
