---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  environment:
    PDR_USER:
      from_secret: docker-user-pdr
    PDR_PASS:
      from_secret: docker-pass-pdr
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/quake2-server:cached --target builder .
  - docker build -t pdr.nephatrine.net/nephatrine/quake2-server:latest .
  - docker build -t pdr.nephatrine.net/nephatrine/quake2-server:nginx . -d Dockerfile.nginx
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker push pdr.nephatrine.net/nephatrine/quake2-server:latest
  - docker push pdr.nephatrine.net/nephatrine/quake2-server:nginx
  - docker logout pdr.nephatrine.net
- name: publish
  environment:
    DOCKER_USER:
      from_secret: docker-user
    DOCKER_PASS:
      from_secret: docker-pass
  commands:
  - docker tag pdr.nephatrine.net/nephatrine/quake2-server:latest nephatrine/quake2-server:latest
  - docker tag pdr.nephatrine.net/nephatrine/quake2-server:nginx nephatrine/quake2-server:nginx
  - docker login -p "$DOCKER_PASS" -u "$DOCKER_USER"
  - docker push -a nephatrine/quake2-server
  - docker logout
  depends_on:
  - build

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-quake2-id
    webhook_token:
      from_secret: wh-quake2-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 7456b29c8c71178364f6004040961b7631b3ff047bc91eb57ea43f655fd195a6

...
