version = 1
SPDX-PackageName = "docker-quake2-yamagi"
SPDX-PackageSupplier = "Daniel Wolf <nephatrine@gmail.com>"
SPDX-PackageDownloadLocation = "https://code.nephatrine.net/NephNET/docker-quake2-yamagi"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/*/dependencies.d/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/user/contents.d/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/*/type"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/opt/quake2-data/*/server.cfg"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/opt/quake2-data/*/.filelist"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/opt/quake2-data/*/.noclient"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
