# SPDX-FileCopyrightText: 2023 Daniel Wolf <nephatrine@gmail.com>
#
# SPDX-License-Identifier: ISC

name: Build Container Image
run-name: ${{ gitea.actor }} pushed to ${{ gitea.repository }}:${{ gitea.ref_name }}
on:
  push:
  schedule:
    - cron:  '40 19 * * 3'
jobs:
  build_amd64:
    if: gitea.repository_owner == 'NephNET' && (!contains(gitea.event.head_commit.message, '#noci') || gitea.event_name == 'schedule')
    runs-on: nephnet-amd64
    steps:
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Build
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-master}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-amd64-cached --target builder ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-amd64 ${{ gitea.workspace }}
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Push
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        run: docker push code.nephatrine.net/nephnet/quake2-yamagi:master-amd64
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "Container Build (X86_64)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  build_i386:
    if: gitea.repository_owner == 'NephNET' && (!contains(gitea.event.head_commit.message, '#noci') || gitea.event_name == 'schedule')
    runs-on: nephnet-i386
    steps:
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Build
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-master}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-i386-cached --target builder --platform linux/386 ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-i386 --platform linux/386 ${{ gitea.workspace }}
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Push
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        run: docker push code.nephatrine.net/nephnet/quake2-yamagi:master-i386
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "Container Build (I686)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  build_arm64:
    if: gitea.repository_owner == 'NephNET' && (!contains(gitea.event.head_commit.message, '#noci') || gitea.event_name == 'schedule')
    runs-on: nephnet-arm64
    steps:
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Build
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-master}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-arm64v8-cached --target builder ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-arm64v8 ${{ gitea.workspace }}
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Push
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        run: docker push code.nephatrine.net/nephnet/quake2-yamagi:master-arm64v8
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "Container Build (AARCH64)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  build_armhf:
    if: gitea.repository_owner == 'NephNET' && (!contains(gitea.event.head_commit.message, '#noci') || gitea.event_name == 'schedule')
    runs-on: nephnet-armhf
    steps:
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Build
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-master}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-armv7-cached --target builder --platform linux/arm/v7 ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-armv7 --platform linux/arm/v7 ${{ gitea.workspace }}
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Push
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        run: docker push code.nephatrine.net/nephnet/quake2-yamagi:master-armv7
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "Container Build (ARMV7L)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  build_riscv64:
    if: gitea.repository_owner == 'NephNET' && (!contains(gitea.event.head_commit.message, '#noci') || gitea.event_name == 'schedule')
    runs-on: nephnet-riscv64
    steps:
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Build
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-master}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-riscv64-cached --target builder ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/quake2-yamagi:${BRANCH}-riscv64 ${{ gitea.workspace }}
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Push
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        run: docker push code.nephatrine.net/nephnet/quake2-yamagi:master-riscv64
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "Container Build (RISCV64)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  build_manifest:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_amd64, build_i386, build_arm64, build_armhf, build_riscv64]
    runs-on: nephnet
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Manifest
        run: |
          docker manifest create code.nephatrine.net/nephnet/quake2-yamagi:latest --amend code.nephatrine.net/nephnet/quake2-yamagi:master-amd64 --amend code.nephatrine.net/nephnet/quake2-yamagi:master-i386 --amend code.nephatrine.net/nephnet/quake2-yamagi:master-arm64v8 --amend code.nephatrine.net/nephnet/quake2-yamagi:master-armv7 --amend code.nephatrine.net/nephnet/quake2-yamagi:master-riscv64
          docker manifest push --purge code.nephatrine.net/nephnet/quake2-yamagi:latest
  publish_amd64:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_amd64]
    runs-on: nephnet-amd64
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Push
        run: |
          docker pull code.nephatrine.net/nephnet/quake2-yamagi:master-amd64
          docker tag code.nephatrine.net/nephnet/quake2-yamagi:master-amd64 nephatrine/quake2-server:yamagi-amd64
          docker push nephatrine/quake2-server:yamagi-amd64
          docker rmi nephatrine/quake2-server:yamagi-amd64
  publish_i386:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_i386]
    runs-on: nephnet-i386
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Push
        run: |
          docker pull code.nephatrine.net/nephnet/quake2-yamagi:master-i386
          docker tag code.nephatrine.net/nephnet/quake2-yamagi:master-i386 nephatrine/quake2-server:yamagi-i386
          docker push nephatrine/quake2-server:yamagi-i386
          docker rmi nephatrine/quake2-server:yamagi-i386
  publish_arm64:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_arm64]
    runs-on: nephnet-arm64
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Push
        run: |
          docker pull code.nephatrine.net/nephnet/quake2-yamagi:master-arm64v8
          docker tag code.nephatrine.net/nephnet/quake2-yamagi:master-arm64v8 nephatrine/quake2-server:yamagi-arm64v8
          docker push nephatrine/quake2-server:yamagi-arm64v8
          docker rmi nephatrine/quake2-server:yamagi-arm64v8
  publish_armhf:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_armhf]
    runs-on: nephnet-armhf
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Push
        run: |
          docker pull code.nephatrine.net/nephnet/quake2-yamagi:master-armv7
          docker tag code.nephatrine.net/nephnet/quake2-yamagi:master-armv7 nephatrine/quake2-server:yamagi-armv7
          docker push nephatrine/quake2-server:yamagi-armv7
          docker rmi nephatrine/quake2-server:yamagi-armv7
  publish_riscv64:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_riscv64]
    runs-on: nephnet-riscv64
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Push
        run: |
          docker pull code.nephatrine.net/nephnet/quake2-yamagi:master-riscv64
          docker tag code.nephatrine.net/nephnet/quake2-yamagi:master-riscv64 nephatrine/quake2-server:yamagi-riscv64
          docker push nephatrine/quake2-server:yamagi-riscv64
          docker rmi nephatrine/quake2-server:yamagi-riscv64
  publish_manifest:
    needs: [publish_amd64, publish_i386, publish_arm64, publish_armhf, publish_riscv64]
    runs-on: nephnet
    steps:
      - name: Check Base Image
        if: gitea.event_name == 'schedule'
        uses: https://github.com/lucacome/docker-image-update-checker@v1
        id: checkbase
        with:
          base-image: nephatrine/alpine-s6:latest
          image: nephatrine/quake2-server:yamagi
          platforms: linux/amd64
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Manifest
        run: |
          docker manifest create nephatrine/quake2-server:yamagi-8.30 --amend nephatrine/quake2-server:yamagi-amd64 --amend nephatrine/quake2-server:yamagi-i386 --amend nephatrine/quake2-server:yamagi-arm64v8 --amend nephatrine/quake2-server:yamagi-armv7 --amend nephatrine/quake2-server:yamagi-riscv64
          docker manifest create nephatrine/quake2-server:yamagi-8 --amend nephatrine/quake2-server:yamagi-amd64 --amend nephatrine/quake2-server:yamagi-i386 --amend nephatrine/quake2-server:yamagi-arm64v8 --amend nephatrine/quake2-server:yamagi-armv7 --amend nephatrine/quake2-server:yamagi-riscv64
          docker manifest create nephatrine/quake2-server:yamagi --amend nephatrine/quake2-server:yamagi-amd64 --amend nephatrine/quake2-server:yamagi-i386 --amend nephatrine/quake2-server:yamagi-arm64v8 --amend nephatrine/quake2-server:yamagi-armv7 --amend nephatrine/quake2-server:yamagi-riscv64
          docker manifest create nephatrine/quake2-server:latest --amend nephatrine/quake2-server:yamagi-amd64 --amend nephatrine/quake2-server:yamagi-i386 --amend nephatrine/quake2-server:yamagi-arm64v8 --amend nephatrine/quake2-server:yamagi-armv7 --amend nephatrine/quake2-server:yamagi-riscv64
          docker manifest push --purge nephatrine/quake2-server:yamagi-8.30
          docker manifest push --purge nephatrine/quake2-server:yamagi-8
          docker manifest push --purge nephatrine/quake2-server:yamagi
          docker manifest push --purge nephatrine/quake2-server:latest
      - name: Notify Discord
        if: gitea.event_name != 'schedule' || steps.checkbase.outputs.needs-updating == 'true'
        uses: https://github.com/sarisia/actions-status-discord@v1
        with:
          title: "DockerHub: quake2-yamagi"
          description: "The container image was pushed to [DockerHub](https://hub.docker.com/repository/docker/nephatrine/quake2-server/general).\nPull `nephatrine/quake2-server:yamagi` for the newest image."
          nodetail: true
          webhook: ${{ secrets.DISCORD_WEBHOOK_PACKAGE }}
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Describe
        uses: https://github.com/peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: nephatrine/quake2-server
