#!/usr/bin/with-contenv bash

if [[ -d /mnt/shared/data/quake2 ]]; then
  cd /mnt/shared/data/quake2
  find . -type f -name 'game.so' -exec s6-setuidgid guardian cp --parents {} /opt/quake2/ \;
  exit 0
elif [[ -d /mnt/config/data/quake2 ]]; then
  cd /mnt/config/data/quake2
  find . -type f -name 'game.so' -exec s6-setuidgid guardian cp --parents {} /opt/quake2/ \;
fi

if [[ ! -d /mnt/config/data/quake2/baseq2 ]]; then
  if [[ ! -e /tmp/q2-314-demo-x86.exe ]]; then
    wget -qO /tmp/q2-314-demo-x86.exe https://files.nephatrine.net/Q2/idstuff/q2-314-demo-x86.exe
  fi
  if [[ ! -e /tmp/q2-3.20-x86-full-ctf.exe ]]; then
    wget -qO /tmp/q2-3.20-x86-full-ctf.exe https://files.nephatrine.net/Q2/idstuff/q2-3.20-x86-full-ctf.exe
  fi
  if [[ ! -e /tmp/match1.tar.gz ]]; then
    wget -qO /tmp/match1.tar.gz https://files.nephatrine.net/Q2/idstuff/match1.tar.gz
  fi
  if [[ ! -e /tmp/dm_64.tar.gz ]]; then
    wget -qO /tmp/dm_64.tar.gz https://files.nephatrine.net/Q2/idstuff/dm_64.tar.gz
  fi
  if [[ -e /tmp/q2-314-demo-x86.exe ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/baseq2
    s6-setuidgid guardian unzip -jq -d /mnt/config/data/quake2/baseq2/ /tmp/q2-314-demo-x86.exe \
     Install/Data/baseq2/pak0.pak \
     Install/Data/DOCS/license.txt
    rm -f /tmp/q2-314-demo-x86.exe
  fi
  if [[ -e /tmp/q2-3.20-x86-full-ctf.exe ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/baseq2
    s6-setuidgid guardian unzip -jq -d /mnt/config/data/quake2/baseq2/ /tmp/q2-3.20-x86-full-ctf.exe \
     baseq2/maps.lst \
     baseq2/pak1.pak \
     baseq2/pak2.pak
    s6-setuidgid guardian mkdir /tmp/q2-3.20-x86-full-ctf
    s6-setuidgid guardian unzip -d /tmp/q2-3.20-x86-full-ctf/ /tmp/q2-3.20-x86-full-ctf.exe
    s6-setuidgid guardian mv /tmp/q2-3.20-x86-full-ctf/baseq2/players /mnt/config/data/quake2/baseq2/
    rm -rf /tmp/q2-3.20-x86-full-ctf
  fi
  if [[ -e /tmp/match1.tar.gz ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/baseq2
    s6-setuidgid guardian tar x -C /mnt/config/data/quake2/baseq2/ -zf /tmp/match1.tar.gz \
     pak3.pak
    rm -f /tmp/match1.tar.gz
  fi
  if [[ -e /tmp/dm_64.tar.gz ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/baseq2/maps
    s6-setuidgid guardian tar x -C /mnt/config/data/quake2/baseq2/maps/ -zf /tmp/dm_64.tar.gz \
     base64.bsp \
     city64.bsp \
     sewer64.bsp
    rm -f /tmp/dm_64.tar.gz
  fi
fi

if [[ ! -d /mnt/config/data/quake2/ctf ]]; then
  if [[ ! -e /tmp/q2-3.20-x86-full-ctf.exe ]]; then
    wget -qO /tmp/q2-3.20-x86-full-ctf.exe https://files.nephatrine.net/Q2/idstuff/q2-3.20-x86-full-ctf.exe
  fi
  if [[ ! -e /tmp/q2ctf150upgrade.zip ]]; then
    wget -qO /tmp/q2ctf150upgrade.zip https://files.nephatrine.net/Q2/q2ctf/q2ctf150upgrade.zip
  fi
  if [[ ! -e /tmp/q2ctf4a.tar.gz ]]; then
    wget -qO /tmp/q2ctf4a.tar.gz https://files.nephatrine.net/Q2/q2ctf/q2ctf4a.tar.gz
  fi
  if [[ -e /tmp/q2-3.20-x86-full-ctf.exe ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/ctf
    s6-setuidgid guardian unzip -jq -d /mnt/config/data/quake2/ctf/ /tmp/q2-3.20-x86-full-ctf.exe \
     ctf/pak0.pak \
     ctf/server.cfg
    rm -f /tmp/q2-3.20-x86-full-ctf.exe
  fi
  if [[ -e /tmp/q2ctf150upgrade.zip ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/ctf
    s6-setuidgid guardian unzip -jq -d /mnt/config/data/quake2/ctf/ /tmp/q2ctf150upgrade.zip \
     pak1.pak
    rm -f /tmp/q2ctf150upgrade.zip
  fi
  if [[ -e /tmp/q2ctf4a.tar.gz ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/ctf/maps
    s6-setuidgid guardian tar x -C /mnt/config/data/quake2/ctf/maps/ -zf /tmp/q2ctf4a.tar.gz \
     q2ctf4a.bsp
    rm -f /tmp/q2ctf4a.tar.gz
  fi
fi

if [[ ! -d /mnt/config/data/quake2/zaero ]]; then
  if [[ ! -e /tmp/zaerodemo.zip ]]; then
    wget -qO /tmp/zaerodemo.zip https://files.nephatrine.net/Q2/zaero/zaerodemo.zip
  fi
  if [[ ! -e /tmp/zaerodm.zip ]]; then
    wget -qO /tmp/zaerodm.zip https://files.nephatrine.net/Q2/zaero/zaerodm.zip
  fi
  if [[ ! -e /tmp/zaero-1.1.zip ]]; then
    wget -qO /tmp/zaero-1.1.zip https://files.nephatrine.net/Q2/zaero/zaero-1.1.zip
  fi
  if [[ -e /tmp/zaerodemo.zip ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/zaero
    s6-setuidgid guardian unzip -jq -d /mnt/config/data/quake2/zaero/ /tmp/zaerodemo.zip \
     zdemo/config.cfg \
     zdemo/pak0.pak
    s6-setuidgid guardian mkdir /tmp/zaerodemo
    s6-setuidgid guardian unzip -d /tmp/zaerodemo/ /tmp/zaerodemo.zip
    s6-setuidgid guardian mv /tmp/zaerodemo/zdemo/sprites /mnt/config/data/quake2/zaero/
    rm -f /tmp/zaerodemo.zip
  fi
  if [[ -e /tmp/zaero-1.1.zip ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/zaero
    s6-setuidgid guardian unzip -jq -d /mnt/config/data/quake2/zaero/ /tmp/zaero-1.1.zip \
     pak1.pak
    rm -f /tmp/zaero-1.1.zip
  fi
  if [[ -e /tmp/zaerodm.zip ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/zaero
    s6-setuidgid guardian unzip -jq -d /mnt/config/data/quake2/zaero/ /tmp/zaerodm.zip \
     pak2.pak
    rm -f /tmp/zaerodm.zip
  fi
fi

if [[ -d /mnt/config/data/quake2/baseq2 && -d /opt/quake2-data/baseq2 ]]; then
  s6-setuidgid guardian cp -Rn /opt/quake2-data/baseq2/* /mnt/config/data/quake2/baseq2/
fi
if [[ -d /opt/quake2-data/3zb2 ]]; then
  if [[ ! -d /mnt/config/data/quake2/3zb2 ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/data/quake2/3zb2
  fi
  s6-setuidgid guardian cp -Rn /opt/quake2-data/3zb2/* /mnt/config/data/quake2/3zb2/
fi
if [[ -d /mnt/config/data/quake2/jugfull && -d /opt/quake2-data/jugfull ]]; then
  s6-setuidgid guardian cp -Rn /opt/quake2-data/jugfull/* /mnt/config/data/quake2/jugfull/
fi
if [[ -d /mnt/config/data/quake2/xatrix && -d /opt/quake2-data/xatrix ]]; then
  s6-setuidgid guardian cp -Rn /opt/quake2-data/xatrix/* /mnt/config/data/quake2/xatrix/
fi
if [[ -d /mnt/config/data/quake2/rogue && -d /opt/quake2-data/rogue ]]; then
  s6-setuidgid guardian cp -Rn /opt/quake2-data/rogue/* /mnt/config/data/quake2/rogue/
fi
if [[ -d /mnt/config/data/quake2/zaero && -d /opt/quake2-data/zaero ]]; then
  s6-setuidgid guardian cp -Rn /opt/quake2-data/zaero/* /mnt/config/data/quake2/zaero/
fi

if [[ ! -z "${QUAKE2_MIRROR}" && "${QUAKE2_MIRROR}" == "true" ]]; then
  if [[ -d /mnt/config/www/quake2 ]]; then
    rm -rf /mnt/config/www/quake2/*
  fi
  /usr/local/bin/quake2-mirror
fi
