#!/usr/bin/with-contenv bash
if pgrep -f quakedock >/dev/null; then
  s6-setuidgid guardian screen -S quakedock -X stuff "`echo -ne \"say QUAKE II SERVER SHUTTING DOWN!\r\"`"
  s6-setuidgid guardian screen -S quakedock -X stuff "`echo -ne \"say 3\r\"`"
  sleep 2
  s6-setuidgid guardian screen -S quakedock -X stuff "`echo -ne \"say 2\r\"`"
  sleep 2
  s6-setuidgid guardian screen -S quakedock -X stuff "`echo -ne \"say 1\r\"`"
  sleep 2
  s6-setuidgid guardian screen -S quakedock -X stuff "`echo -ne \"quit\r\"`"
  sleep 2
fi
